webtalk_init -webtalk_dir /home/zanpoole/School/EE316/Interrupt/Interrupt.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2023-04-04 11:41:23" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "212361173_0_0_425" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "crriutaob7ssu8rf96bic0geo" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2019.1_3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Linuxmint" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Linux Mint 21.1" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 3700X 8-Core Processor" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2200.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "33.564 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1680617307000" -context "sdk\\\\bsp/1680617307000"
webtalk_add_data -client sdk -key hwid -value "1680613830000" -context "sdk\\\\bsp/1680617307000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1680617307000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1680617307000"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1680617307000"
webtalk_add_data -client sdk -key uid -value "1680617308000" -context "sdk\\\\application/1680617308000"
webtalk_add_data -client sdk -key hwid -value "1680613830000" -context "sdk\\\\application/1680617308000"
webtalk_add_data -client sdk -key bspid -value "1680617307000" -context "sdk\\\\application/1680617308000"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1680617308000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1680617308000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1680617308000"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1680617308000"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1680617308000"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1680617308000"
webtalk_add_data -client sdk -key projSize -value "207.51953125" -context "sdk\\\\application/1680617308000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1680622883807"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1680622883807"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1680622883807"
webtalk_add_data -client sdk -key DebugCount -value "9" -context "sdk\\\\bsp/1680622883807"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1680622883807"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1680622883807"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1680622883807"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1680622883807"
webtalk_transmit -clientid 3008623779 -regid "212361173_0_0_425" -xml /home/zanpoole/School/EE316/Interrupt/Interrupt.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/zanpoole/School/EE316/Interrupt/Interrupt.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/zanpoole/School/EE316/Interrupt/Interrupt.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
